### PR TITLE
fix: check if speechSynthesis is undefined

### LINKED ISSUE #446: [Bug] Can not use version v0.0.34 in the Ubuntu 22.04
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.34

### 系统/浏览器版本 System/Browser version

Ubuntu 22.04

### 复现步骤 Reproduce step

Install via:

```sh
sudo dpkg -i open-ai-translator_0.0.34_amd64.deb
```

No problem in the installation process, but cannot open it, always black window.

image

### 你看到了什么错误？What errors do you see?

No errors

### 你期望看到什么？What did you expect to see?

I can use it like the browser extention.

### 还有其他的内容吗？Anything else?

_No response_

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

### LINKED ISSUE #474: [Bug] Ubuntu Wayland 桌面版白屏
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.34 AppImage

### 系统/浏览器版本 System/Browser version

Ubuntu 22.04 LTS, 5.19.0-35-generic, wayland, sway desktop

### 复现步骤 Reproduce step

安装 v0.0.34 AppImage, 从系统托盘图标打开应用 (Show)

### 你看到了什么错误？What errors do you see?

白屏

### 你期望看到什么？What did you expect to see?

正常工作

### 还有其他的内容吗？Anything else?

- 系统托盘图标正常
- 白屏窗口右键菜单可以显示
  image
- v0.0.27 窗口可以正常打开, 大部分功能正常
- v0.0.28 及以上都有这问题
- deb 版本同样

感谢各位作者的努力. 我并不着急修复, 只是提醒其他类似用户先使用旧版或者浏览器插件.

我明白使用 linux, wayland 桌面环境的是少数用户, 修复起来也很麻烦. 而且就算修复了这个问题, 还有很多其他问题, 例如之前观察到输入框不支持 IME (fcitx5 + rime).

我不太熟悉桌面开发, 哪位朋友有兴趣的话我可以配合 debug.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by maltoze**
`speechSynthesis` may be undefined on Ubuntu.

fix #474
fix #446 
#451 

~don't know what's this~
```
Error: permission denied for this operation, plese try as super user
Thumb window does not exist
```
image

### CODE REVIEW

File: src/common/tts.ts [hunk 1]
```diff
@@ -36,9 +36,11 @@ export const supportTTSLang: Record<string, string> = {
     'vi': 'vi-VN',
 }
 
-let supportVoices: SpeechSynthesisVoice[]
-window.speechSynthesis.onvoiceschanged = () => {
-    supportVoices = speechSynthesis.getVoices()
+let supportVoices: SpeechSynthesisVoice[] = []
+if (typeof window.speechSynthesis !== 'undefined') {
```
Comment (yetone) [inline src/common/tts.ts:40]:
```suggestion
if (window.speechSynthesis) {
```

**Comment by yetone** [comment]
I'm sorry, I introduced conflicts.
