### PR TITLE
Fix popup position

### LINKED ISSUE #202: [Bug] 还是会有不能移动的问题
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.17

### System version

Win10 LTSC 1809

### Browser version

Chrome 110.0.5481.180

### Minimal reproduce step

https://user-images.githubusercontent.com/48620527/224475498-3eb43e68-3271-4e83-8349-1320ffd5f497.mp4

### What did you expect to see?

显示翻译文本的区域，当行数超出设定的时候，加一个文本域

### What did you see instead?

翻译行数过多的时候，还会有不能纵向移动的问题

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by imyuanx**
- Positioning base on document
- The maximum height equals the visible window

Close #202 

openai-translator-scroll-last

### CODE REVIEW

File: src/content_script/PopupCard.tsx [hunk 1]
```diff
@@ -24,7 +24,8 @@ import { ErrorBoundary } from 'react-error-boundary'
 import { ErrorFallback } from '../components/ErrorFallback'
 import { getBrowser, getSettings, isDesktopApp, ISettings } from '../common/utils'
 import { Settings } from '../popup/Settings'
-import { calculateMaxTop } from '.'
+import { calculateMaxXY } from '.'
```
Comment (yetone) [inline src/content_script/PopupCard.tsx:27]: We cannot import anything from index.tsx in PopupCard because it will cause nested rendering issues in Tauri applications. In the future, we will consider moving PopupCard to a suitable location to prevent this situation from being accidentally introduced.

https://github.com/yetone/openai-translator/issues/226

**Comment by yetone** [comment]
LGTM!

File: src/content_script/PopupCard.tsx (hunk 1 above)
Comment (imyuanx) [reply src/content_script/PopupCard.tsx:27]: Okay, this function calculates the position of `PopupCard`, I think we can temporarily move to `src/content_script/utils.ts`, what do you think?

Comment (yetone) [reply src/content_script/PopupCard.tsx:27]: @imyuanx Great idea. I already moved `calculateMaxTop` to the utils yesterday.

Comment (imyuanx) [reply src/content_script/PopupCard.tsx]: I see. Now the conflict has been resolved!

**Comment by imyuanx** [comment]
The conflict has been resolved! Need review again, Ty @yetone

**Comment by imyuanx** [comment]
Done!

**Comment by yetone** [comment]
LGTM!
